### ISSUE TITLE
Is there a video?

### ISSUE THREAD

**Issue by ThorodanBrom** [sangorrin/linuxcon-japan-2015#1]
Hello. Just wanted to know if your talk was recorded, and is online somewhere. I find the content very relevant 3 years later. If you've given a similar talk elsewhere, that would be fine too.

Thanks!

**Comment by sangorrin** [comment]
Unfortunately, it was not recorded as far as I know. I'm glad that you still find it relevant, thank you. After the talk, I sent an RFC with my Seccomp modifications to the kernel mailing list, but it was rejected. This patch was still not mature, but I wanted to have some feedback before it was too late:
https://lore.kernel.org/patchwork/patch/637918/
https://lkml.org/lkml/2016/1/24/380

On the same line of my talk (using determinism to protect the system), we (Toshiba) submitted a new LSM module to the kernel called Whiteegret (https://github.com/whiteegret/whiteegret). It allows you to create a whitelist defining what files in your device can execute and their hashes.

Which part of the talk are you more interested in?

Thanks
Daniel

**Comment by ThorodanBrom** [comment]
Something I'm working on currently could benefit from security via determinism, so I'm really interested in that part of your talk. I'm trying to understand what all can be the 'constants' that I can check to detect a compromised system, while not affecting performance. 

I've understood what you've conveyed in the slides. I'm sure you would have elaborated on some things during the talk, which is why I asked if there was a recording. WhiteEgret looks very useful, thanks!

**Comment by sangorrin** [comment]
The constants depend on the actual system you have. For example, if you have a real-time embedded system, you normally have specific periods for tasks and tasks do not use system calls that may cause threads to sleep such as reading or writing a file. A white list of binaries that can execute on a particular board, like the one proposed in whiteEgret, is another example. If you go on with the investigation and get to make some presentation please let me know. Thanks!
